SGE.WebconAutenticacion/Areas/Adm/Controllers/CatalogosController.cs
using SGE.Entidades.Acciones;
using SGE.Entidades.Contexto;
using SGE.Entidades.Dispositivos;
using SGE.Entidades.Sensores;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace SGE.WebconAutenticacion.Areas.Adm.Controllers {
    public class CatalogosController : Controller {
        private SGEContext db = new SGEContext();

        // GET: Adm/Dispositivos
        public ActionResult Index() {
            var catalogo = db.Catalogos.Include(c => c.Administrador);
            return View(catalogo.ToList());
        }

        // GET: Adm/Dispositivos/Details/
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catalogo catalogo = db.Catalogos.Include("Acciones").Include("Sensores").FirstOrDefault(c => c.Id == id);
            if (catalogo == null) {
                return HttpNotFound();
            }
            return View(catalogo);
        }

        // GET: Adm/Dispositivos/Create
        public ActionResult Create() {
            ViewBag.AdministradorId = new SelectList(db.Usuarios, "Id", "Nombre");
            ViewBag.Acciones = new MultiSelectList(db.Acciones, "Id", "Descripcion");
            ViewBag.Sensores = new MultiSelectList(db.Sensores, "Id", "Descripcion");
            return View();
        }

        // POST: Adm/Dispositivos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Catalogo catalogo, int[] sensoresIds, int[] accionesIds) {
            catalogo.Sensores = setearSensores(sensoresIds);
            catalogo.Acciones = setearAcciones(accionesIds);

            if (ModelState.IsValid) {
                db.Catalogos.Add(catalogo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AdministradorId = new SelectList(db.Usuarios, "Id", "Nombre", catalogo.AdministradorId);
            return View(catalogo);
        }

        // GET: Adm/Dispositivos/Edit/
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catalogo catalogo = db.Catalogos.Find(id);
            if (catalogo == null) {
                return HttpNotFound();
            }
            ViewBag.AdministradorId = new SelectList(db.Usuarios, "Id", "Nombre", catalogo.AdministradorId);
            ViewBag.Acciones = new MultiSelectList(db.Acciones, "Id", "Descripcion", db.Acciones.Where(a => a.Catalogos.Any(c => c.Id == id)).Select(a => a.Id).ToArray());
            ViewBag.Sensores = new MultiSelectList(db.Sensores, "Id", "Descripcion", db.Sensores.Where(s => s.Catalogos.Any(c => c.Id == id)).Select(s => s.Id).ToArray());
            return View(catalogo);
        }

        // POST: Adm/Dispositivos/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Catalogo catalogo, int[] sensoresIds, int[] accionesIds) {
            catalogo.Sensores = setearSensores(sensoresIds);
            catalogo.Acciones = setearAcciones(accionesIds);
            if (ModelState.IsValid) {
                Catalogo catalogoBase = db.Catalogos.Include("Acciones").Include("Sensores").First(c => c.Id == catalogo.Id);

                catalogoBase.Sensores = catalogo.Sensores;
                catalogoBase.Acciones = catalogo.Acciones;

                db.Entry(catalogoBase).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.AdministradorId = new SelectList(db.Usuarios, "Id", "Nombre", catalogo.AdministradorId);
            ViewBag.Acciones = new MultiSelectList(db.Acciones, "Id", "Descripcion", catalogo.Acciones.Select(a => a.Id).ToArray());
            ViewBag.Sensores = new MultiSelectList(db.Sensores, "Id", "Descripcion", catalogo.Sensores.Select(s => s.Id).ToArray());
            return View(catalogo);
        }

        // GET: Adm/Dispositivos/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Catalogo catalogo = db.Catalogos.Find(id);
            if (catalogo == null) {
                return HttpNotFound();
            }
            return View(catalogo);
        }

        // POST: Adm/Dispositivos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Catalogo catalogo = db.Catalogos.Find(id);
            db.Catalogos.Remove(catalogo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private List<Sensor> setearSensores(int[] sensoresIds) {
            List<Sensor> sensores = new List<Sensor>();
            Sensor sensor = null;

            foreach(int sensorId in sensoresIds) {
                sensor = db.Sensores.FirstOrDefault(s => s.Id == sensorId);
                if(sensor != null) {
                    sensores.Add(sensor);
                }
            }

            return sensores;
        }

        private List<Accion> setearAcciones(int[] accionesIds) {
            List<Accion> acciones = new List<Accion>();
            Accion accion = null;

            foreach (int accionId in accionesIds) {
                accion = db.Acciones.FirstOrDefault(a => a.Id == accionId);
                if(accion != null) {
                    acciones.Add(accion);
                }
            }

            return acciones;
        }
    }
}

SGE.WebconAutenticacion/Areas/Cli/Controllers/CargaMasivaController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using SGE.Entidades.Contexto;
using SGE.Entidades.Dispositivos;
using SGE.Entidades.Repositorio;
using SGE.Entidades.Sensores;
using SGE.Entidades.Sesion;
using SGE.Entidades.Usuarios;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGE.WebconAutenticacion.Areas.Cli.Controllers {
    public class CargaMasivaController : Controller {
        // GET: Cli/CargaMasiva
        public ActionResult Index() {
            return View();
        }

        // GET: Cli/CargaMasiva/Details/5
        public JsonResult SubirArchivo(HttpPostedFileBase File) {
            if (!File.ContentType.Contains("json")) {
                return Json(new { success = false, error = "El archivo debe ser de formato JSON" });
            }

            try {
                using (StreamReader r = new StreamReader(File.InputStream)) {
                    string json = r.ReadToEnd();
                    List<Inteligente> inteligentes = JsonConvert.DeserializeObject<List<Inteligente>>(json);

                    var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                    var user = UserManager.FindById(User.Identity.GetUserId());

                    SGEContext contexto = new SGEContext();

                    BaseRepositorio<Cliente> repoCliente = new BaseRepositorio<Cliente>(contexto);
                    Cliente cliente = repoCliente.Single(c => c.NombreUsuario == user.UserName);

                    BaseRepositorio<Catalogo> repoCatalogo = new BaseRepositorio<Catalogo>(contexto);
                    BaseRepositorio<Inteligente> repoInteligente = new BaseRepositorio<Inteligente>(contexto);

                    foreach (Inteligente inteligente in inteligentes) {
                        Catalogo Catalogo = repoCatalogo.Single(c => c.Id == inteligente.CatalogoId);

                        if(Catalogo == null) {
                            return Json(new { success = false, error = "El dispositivo '" + inteligente.Nombre + "' esta asociado a un catálogo inexistente" });
                        }
                        string nombreInteligente = Catalogo.Nombre + "_" + DateTime.Now.ToString("ddMMyyHHmmss");
                        nombreInteligente = nombreInteligente.Replace(" ", "_");
                        inteligente.Nombre = nombreInteligente;
                        inteligente.Clientes.Clear();
                        inteligente.Clientes.Add(cliente);

                        if (inteligente.Id != 0) {
                            repoInteligente.Update(inteligente);
                        } else {
                            repoInteligente.Create(inteligente);
                        }

                        List<Sensor> sensores = contexto.Sensores.Where(s => s.Catalogos.Any(c => c.Id == Catalogo.Id)).ToList();

                        foreach (Sensor sensor in sensores) {
                            SGEContext db2 = new SGEContext();
                            SensorFisico sensorFisico = new SensorFisico() {
                                //TipoSensor = sensor,
                                //Dispositivo = inteligente,
                                IdDispositivo = inteligente.Id,
                                IdTipoSensor = sensor.Id,
                                Descripcion = sensor.Descripcion
                            };
                            sensorFisico.Mediciones = null;
                            //repoSensorFisico.Create(sensorFisico);
                            db2.SensoresFisicos.Add(sensorFisico);
                            db2.SaveChanges();
                        }
                    }
                }
            } catch (Exception ex) {
                return Json(new { success = false, error = "El archivo JSON no es valido, por favor verifique el mismo", mensaje = ex.Message });
            }

            return Json(new { success = true });
        }
    }
}

SGE.WebconAutenticacion/Areas/Cli/Controllers/ConsumoController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SGE.Entidades.Contexto;
using SGE.Entidades.Reportes;
using SGE.Entidades.Repositorio;
using SGE.Entidades.Sesion;
using SGE.Entidades.Usuarios;
using System;
using System.Web.Mvc;

namespace SGE.WebconAutenticacion.Areas.Cli.Controllers {
    public class ConsumoController : Controller
    {
        // GET: Cliente/Consumo
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Buscar(string fechaDesde, string fechaHasta) {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var user = UserManager.FindById(User.Identity.GetUserId());

            SGEContext contexto = new SGEContext();

            BaseRepositorio<Cliente> repoCliente = new BaseRepositorio<Cliente>(contexto);
            Cliente cliente = repoCliente.Single(c => c.NombreUsuario == user.UserName);

            DateTime fDesde = Convert.ToDateTime(fechaDesde);
            DateTime fHasta = DateTime.Now;

            if (!String.IsNullOrEmpty(fechaHasta)) {
                fHasta = Convert.ToDateTime(fechaHasta);
            }

            var consumo = Reporte.consumoPorHogarYPeriodo(cliente.Id, fDesde, fHasta);
            return Json(new { success = true, resultado = consumo });
        }
    }
}

SGE.WebconAutenticacion/Areas/Cli/Controllers/HogarEficienteController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SGE.Entidades.Contexto;
using SGE.Entidades.Dispositivos;
using SGE.Entidades.Repositorio;
using SGE.Entidades.Sesion;
using SGE.Entidades.Usuarios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web.Mvc;

namespace SGE.WebconAutenticacion.Areas.Cli.Controllers {
    public class HogarEficienteController : Controller {
        // GET: Cli/HogarEficiente
        public ActionResult Index() {
            Dictionary<string, double> resultadoSimplex = ejecucionSimplex();

            if (resultadoSimplex != null) {
                ViewBag.ConsumoRestanteTotal = resultadoSimplex["ConsumoRestanteTotal"];
                ViewBag.ResultadoSimplex = resultadoSimplex;
            }

            return View();
        }

        public JsonResult ejecutarSimplex() {
            Dictionary<string, double> resultadoSimplex = ejecucionSimplex();
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var user = UserManager.FindById(User.Identity.GetUserId());
            SGEContext db = new SGEContext();

            if (resultadoSimplex == null) {
                return Json(new { success = false, error = "No se puede ejecutar el simplex" });
            }

            BaseRepositorio<Inteligente> repoInteligente = new BaseRepositorio<Inteligente>(db);
            var includesCliente = new List<Expression<Func<Inteligente, object>>>() {
                i => i.RegistroDeActivaciones,
                i => i.Clientes
            };
            Inteligente inteligente = null;
            foreach (KeyValuePair<string, double> item in resultadoSimplex) {
                if(item.Value > 0 && item.Key != "TotalHorasRestantes" && item.Key != "ConsumoRestanteTotal") {
                    inteligente = repoInteligente.Single(i => i.Nombre == item.Key && i.Clientes.Any(c => c.NombreUsuario == user.UserName), includesCliente);
                    inteligente.Encender();
                    repoInteligente.Update(inteligente);
                }
            }

            return Json(new { success = true });
        }

        private Dictionary<string, double> ejecucionSimplex() {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var user = UserManager.FindById(User.Identity.GetUserId());

            SGEContext db = new SGEContext();

            BaseRepositorio<Inteligente> repoInteligente = new BaseRepositorio<Inteligente>(db);
            var includesCliente = new List<Expression<Func<Inteligente, object>>>() {
                i => i.RegistroDeActivaciones,
                i => i.Clientes
            };
            List<Inteligente> inteligentes = repoInteligente.Filter(i => i.Clientes.Any(c => c.NombreUsuario == user.UserName), includesCliente);

            Cliente cliente = new Cliente();

            cliente.Inteligentes = inteligentes;

            return cliente.HogarEficiente();
        }
    }
}

SGE.WebconAutenticacion/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.Owin;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>>@ViewBag.Title - SGE - Sistema de Gestión Energética</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/filestyle")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SGE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.GetUserId() == null) {
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    } else {
                        var userManager = Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
                        var roles = userManager.GetRoles(User.Identity.GetUserId());

                        if (roles.Any(r => r == "Admin")) {
                            <li>@Html.ActionLink("Hogares", "Index", "Hogares", new { area = "Adm" }, null)</li>
                            <li>@Html.ActionLink("Reportes", "Index", "Reportes", new { area = "Adm" }, null)</li>
                            <li>@Html.ActionLink("Catalogos dispositivos", "Index", "Catalogos", new { area = "Adm" }, null)</li>
                            <li>@Html.ActionLink("Dispositivos", "Index", "Dispositivos", new { area = "Adm" }, null)</li>
                        } else {
                            <li>@Html.ActionLink("Hogar", "Index", "Hogar", new { area = "Cli" }, null)</li>
                            <li>@Html.ActionLink("Consumo por período", "Index", "Consumo", new { area = "Cli" }, null)</li>
                            <li>@Html.ActionLink("Hogar eficiente", "Index", "HogarEficiente", new { area = "Cli" }, null)</li>
                            <li>@Html.ActionLink("Reglas", "Index", "Reglas", new { area = "Cli" }, null)</li>
                            <li>@Html.ActionLink("Dispositivos", "Index", "Dispositivos", new { area = "Cli" }, null)</li>
                            <li>@Html.ActionLink("Carga masiva dispositivos", "Index", "CargaMasiva", new { area = "Cli" }, null)</li>
                        }
                    }
                    <li>@Html.ActionLink("Mapa", "Index", "Mapa", new { area = "" }, null)</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SGE - Sistema de Gestión Energética - Diseño de Sistemas</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>